### ISSUE TITLE
RSSフィード内のURLが404

### ISSUE THREAD

**Issue by buchizo** [jpazpaas/blog#14]
[RSS Feed](https://jpazpaas.github.io/blog/feed.xml)内のコンテンツURLのホスト名が github.com のためそのままアクセスすると404になってしまいます。

- Feed内のURL例： https://github.com/jpazpaas/blog/2020/11/04/apim-content-length-mismatch.html
- 実際のコンテンツのURL： https://jpazpaas.github.io/blog/2020/11/04/apim-content-length-mismatch.html

**Comment by takmnagayams** [comment]
@buchizo ご指摘ありがとうございます...!
@shibayan に修正いただいたので、クローズとなりました。
