### ISSUE TITLE
Don't support auto redirect after change to new URL, but..

### ISSUE THREAD

**Issue by buchizo** [jpazpaas/blog#262]
[こちらに記載](https://jpazpaas.github.io/blog/2024/01/26/change-paas-blog-url.html)のある通り新URLへ移行後、旧ページからのリダイレクトは行わない件についてですが、旧Blogは維持されるのでしょうか？

もし旧Blogが維持されるのであれば旧記事の先頭に新記事のURLを追記するなど工夫できれば良いと思いますがどうでしょうか？
インフラ的な自動リダイレクトは難しくても各ページ単位で工夫できる余地はありそうな気はしますが如何でしょうか。

**Comment by komayama** [comment]
いつも Azure Paas ブログをご覧くださり誠にありがとうございます。
大変申し訳ございませんが、旧Blog は維持されないためご承知いただけますでしょうか。

理由としては、弊社都合で大変申し訳ございませんが、本ブログ（リポジトリ）の組織（jpazpaas）が 組織（Azure）への統合が必要となり、組織（jpazpaas）は閉鎖する方針となっております。

弊社内でもリダイレクトについて、慎重に検討を重ねましたが、GitHub Pages の仕様によりリダイレクトは難しいため、ご容赦頂ければ幸いです。

https://docs.github.com/ja/repositories/creating-and-managing-repositories/transferring-a-repository#whats-transferred-with-a-repository
> しかし、リポジトリに関連付けられている GitHub Pages はリダイレクトされません。
 
しかしながら、何かしらのお役に立てればと考えており、ブログ記事内で参照しております 旧 ブログ URL は移行後には、運営側で変更を進めて参ります。

**Comment by buchizo** [comment]
jpazpaasのblogリポジトリを新しい組織(Azure)に統合しないといけないのは了解です。
現jpazpaasを会社で維持するのが難しいということであればそのまま第三者に移譲したりできないものかなと思いましたがどうでしょうか。（コンテンツの中身は全部空（リダイレクトURLだけ記載しているようなもの）にして、第三者が現URL系を維持するだけとか、、
それも難しいということであれば諦めるしかありませんが。

**Comment by komayama** [comment]
大変心苦しい限りではございますが、jpazpaas 組織は弊社内のリソースとなり、第三者へ移譲したり所有権を譲渡することは難しい状況でございます。第三者が現 URL を維持する部分につきましても、関係者外の方がリソースへアクセスを行い管理することになり、弊社としても責任を負うことが大変困難でございますためご容赦いただけますでしょうか。

**Comment by buchizo** [comment]
ご確認ありがとうございます。難しい旨了解です。残念です。
